stages:
  - linting
  - testing
pylint:
  stage: linting
  image: registry.gitlab.com/mafda/python-linting
  script:
    - flake8 --ignore=E501,F811,W292,E711,F821,F401 .
  only:
    - merge_requests
    - pushes
pytest:
  stage: testing
  image: python:3.11
  before_script:
    - pip install -r --no-use-pep517 requirements.txt
  script:
    - pytest backend/test.py
  only:
    - pushes
